### ISSUE TITLE
Add iPod Touch 2G Support

### ISSUE THREAD

**Issue by chrisjn123** [LukeZGD/Legacy-iOS-Kit#289]
iPod Touch 2G is not supported but would be a good candidate for additional support.

**Comment by LukeZGD** [comment]
This will be possible since I just got a touch 2 recently.. I'll look into it as I'm also working on something related to greenpois0n

**Comment by LukeZGD** [comment]
I have decided to not add support for it.. Since the older iOS devices including the touch 2 can just restore to any iOS version, it would be easier to just downgrade to 4.0 or lower then jailbreak with JailbreakMe.

idevicerestore or (older) iTunes can be used to restore

JailbreakMe 2.0 (Star) can be used to jailbreak

Older IPSWs for iPod touches can be found here: https://invoxiplaygames.uk/ipsw/

For better support for these older devices, you can check out r/LegacyJailbreak and its Discord server

**Comment by chrisjn123** [comment]
Understandable!
Thanks for the comments appreciate a responsive dev!

I was not aware that I could restore an iTouch 2G to any iOS version. 
Would that allow downgrades to iOS 3.x?

**Comment by LukeZGD** [comment]
Yes you can downgrade to 3.x, not sure if it needs to be a custom IPSW though, you can create one with sn0wbreeze or redsn0w if needed

**Comment by LukeZGD** [comment]
iPod touch 2 support has been added in v23.06.07 (969264a)
