### ISSUE TITLE
iPhone 5c ramdisk

### ISSUE THREAD

**Issue by userse31** [LukeZGD/Legacy-iOS-Kit#290]
(God, why the HELL did I buy this thing!?)

This is under Debian 12.

The issue is that restore.sh uses "ipwndfu" instead of "ipwnder".

./restore.sh

Other Utilities->SSH Ramdisk->N

ipwndfu runs. Promptly hangs the phone, and irritates the USB subsystem in linux.

At this point the phone is no longer detected. The only option is to hard reset the device.

**Comment by LukeZGD** [comment]
> The issue is that restore.sh uses "ipwndfu" instead of "ipwnder".

This is intentional, A6 devices can only be pwned with ipwndfu on Linux (ipwnder/gaster will not work)

> ipwndfu runs. Promptly hangs the phone

This is pretty much expected when it comes to checkm8 on Linux (low success rates). The only things I can suggest are to try on a Mac or [pwning with another iOS device](https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Pwning-Using-Another-iOS-Device)

**Comment by userse31** [comment]
Well fuck.

The mac os vm is a dead end, and I only got ipwndfu to work ONCE.

ONCE. Only ONE time. And I have ZERO clue what did it.

I do have an iphone 7 laying around that I have full access to. Can I just chop a lightning cable up and use that? 

I really hope so...

**Comment by userse31** [comment]
Future update: I ended up going with the lightning OTG cable.

However...

Part of the issue with ipwnder under linux seems to be less with the program itself, and more with how the usb system under linux and the iphone 5c interact. The solution seems to be to quickly unplug and plug the phone until it shows up in dmesg properly.
