### ISSUE TITLE
Alternative iOS 8.4.1 downgrade method

### ISSUE THREAD

**Issue by gamer191** [LukeZGD/Legacy-iOS-Kit#311]
I haven't tested either method, but is there a reason this tool factory resets devices, instead of just using this method?
https://www.youtube.com/watch?v=_JsDblG92NM

**Comment by LukeZGD** [comment]
That method is garbage and messes up devices. I would not recommend it to anyone, avoid.

**Comment by LukeZGD** [comment]
Even if you proceed to do that garbage method, you will NEED to perform an Erase All Content and Settings if you want your device to function

**Comment by gamer191** [comment]
Thank you for the clarification. I have 4 more questions, all of which are pure curiosity (because I don't have an legacy devices), so feel free to ignore them:
1. this tool says it doesn't support downgrading the iPhone 5C to iOS 8.4.1. Theoretically, if someone felt like being a daredevil, could they flash an iPhone 5 firmware onto their iPhone 5C, given the two devices are almost identical?
2. why does this tool factory reset devices? Is it necessary for the exploit to work, or is it just to prevent something going wrong (such as an iOS 9 app being installed on an iOS 8 device)?
3. [according to AppleDB](https://appledb.dev/firmware/iOS/10A101.html), Apple had an internal build of iOS 6 that supported the iPhone 5S 
4. Can this program jailbreak iOS 8.4.1? If yes, how, given both Home Depot and EtasonJB require users to first sign an IPA?

**Comment by LukeZGD** [comment]
1. No. Just use [n1ghtshade](https://github.com/synackuk/n1ghtshade)
2. It is required to do a full reset when downgrading in order for the device to work properly. You will get a lot of issues otherwise
3. No
4. Yes, but it does not use Home Depot or EtasonJB (they're both bad tbh). It uses daibutsu, and it is installed through the creation and usage of a custom IPSW

**Comment by gamer191** [comment]
Thanks for the super quick responses. I have a few questions based on that:
1. Don't IPSW files need to be signed by Apple?
2. what about on all the devices daibutsu doesn't support (according to it's website)?
3. how do you make custom IPSWs? Can you theoretically use it to install any unsigned app?

**Comment by LukeZGD** [comment]
1. Yes, but for unsigned firmwares, SHSH blobs can be used for untethered downgrades. For signed firmwares like 8.4.1 and 6.1.3, we can just grab those blobs anytime and use them. But if it is unsigned, the user must be provide them. For tethered downgrades like n1ghtshade, no SHSH blobs are used, but with the downside of being, well, tethered.
    - There also exists untethered downgrades without SHSH blobs for devices like the 3GS, and Legacy iOS Kit supports those too.
2. Legacy iOS Kit has an updated version of daibutsu that supports all 32-bit devices on iOS 8.0-8.4.1, provided by dora/kok3shidoll. https://twitter.com/kok3shiDev/status/1681495475726467073
3. In general, you use xpwn's ipsw utility. In the case of Legacy iOS Kit, it gets complicated since it is depending on device, target version, and other stuff. Maybe I can do a full documentation of the script and how it uses the tools someday
