### ISSUE TITLE
iPhone 5c and iPhone 3gs tethered boot issues.

### ISSUE THREAD

**Issue by userse31** [LukeZGD/Legacy-iOS-Kit#331]
When selecting the "Just boot" option for a tethered boot and entering the build id for ios 10.3.3 (14G60), the script fails to download the ipsw, or extract it, or... something?

After "init done" is printed, an error is thrown about "Firmware/dfu/iBSS.n48ap.RELEASE.dfu" being non existance. Sure enough, not even that folder exists.

-Things worthy of note-
Everything _almost_ works fine if entering the default value (9B206). However, the phone soft locks at the verbose kmsg screen, never booting further. Odd, and the same as when I set rd=disk0s1s1 as a test.

Trying my iphone 3gs and entering "10B500", the phone stays on the black recovery screen.

So close, yet so far...

Such is life when debugging software!

**Comment by LukeZGD** [comment]
For the 5C 10.3.3 boot, that will not work with the current script. The structure of iOS 10 IPSWs are a bit different, and I didn't expect anyone to do iOS 10 tethered booting, so I never really considered adding the conditions/checks for it.

As for 3GS 6.1.6 boot, I also get the same issue, I have no idea why it happens. iBoot32Patcher issue maybe? It works fine for booting other devices though (tested on iPhone 5 8.x, iPad 3 5.1.1)

**Comment by userse31** [comment]
Hmm... Interesting. Wish my iPod touch 2g was in working order.

So... ios 10 ipsw's... How are they different? As I am one of those "unexpected people" who want to tether boot a 5c on ios 10.

Actually, how _does_ a tethered boot work? (rootfs wise) Do I set rd to a disk partition, or does it load a ramdisk that contains all the init stuff for bringing the system up?

The closest experience I have to this is those time's I messed with putting linux on floppy disks.

I know (very roughly) how linux loads the init process, but zero clue how BSD does it, and that's the issue I'm running into. Kernel panics due to not finding init, or soft locking on the verbose kmsg screen/apple logo with progress bar.

**Comment by LukeZGD** [comment]
here's the best visuals for the 32-bit ios bootchain https://github.com/kjaz89/cherryflowerJB/blob/master/doc/32-bit_iOS_Boot.pdf

for tether boots, check the "just boot" slide. you can do a verbose boot by patching the ibec (or ibss for ios 4 and lower) bootargs with `-v` (no need for anything else, rd should only be used with restore/update)

for ios 10 ipsws, its not that much of a difference really, they just started using 1 ipsw for multiple devices instead of 1 ipsw for each device, so some firmware components are shared between devices. this will be an easy fix

**Comment by LukeZGD** [comment]
Tether boot issues are fixed in v23.10.01 (b13a96e), but I still can't figure out why it doesn't have verbose boot in some cases. Here's the results from the tests I did:

With verbose output: iPhone 5 8.4.1, iPad 3 5.1.1, iPhone 3GS 4.3.3
No verbose output: iPhone 5 10.3.4, iPhone 3GS 6.1.6

All of them boot successfully though, which is the important part I think. The verbose thing is a different issue, so I'll be closing this for now

**Comment by userse31** [comment]
Huh, so I did guess rootdev correctly, just didn't understand everything fully.

**Comment by userse31** [comment]
Can confirm tethered boot of iOS 10.3.3 (14G60) works on iPhone 5c.
