### ISSUE TITLE
More Support

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#337]
here is what i would like to see in Legacy iOS Kit

iOS 4.2.x powdersn0w support for iPhone 4 CDMA

powdersn0w support for ALL iPad 2, iPad 3 and iPad Mini 1 Models with iOS 7.1.x Blobs required 

powdersn0w support for iPad 4 with iOS 7.1.x Blobs required 

iOS 4.0-4.2.1 Support for iPhone 4 GSM with Powdersn0w 

Port powdersn0w to iOS 6 Base Devices for iPhone 4s iPad 2 and iPod Touch 4G for untethered downgrades 

Downgrades for iPad 1 and iPod Touch 3G with the iOS 5 HFS Overflow iBoot Exploit

Support for Jailbreaking 64 Bit Devices with SSH Ramdisk iOS 7.0-9.1

Add iOS 4.3.x iPad 2 Support to g1bertJB

**Comment by LukeZGD** [comment]
> - powdersn0w support for ALL iPad 2, iPad 3 and iPad Mini 1 Models with iOS 7.1.x Blobs required
> - powdersn0w support for iPad 4 with iOS 7.1.x Blobs required

These are possible, but will not be done by me. I don't know how to create exploit ramdisks

> - iOS 4.2.x powdersn0w support for iPhone 4 CDMA
> - iOS 4.0-4.2.1 Support for iPhone 4 GSM with Powdersn0w

I'll see what I can do

> - Port powdersn0w to iOS 6 Base Devices for iPhone 4s iPad 2 and iPod Touch 4G for untethered downgrades

I don't think this is possible, but if it is, hopefully someone does it eventually

> - Downgrades for iPad 1 and iPod Touch 3G with the iOS 5 HFS Overflow iBoot Exploit

I plan to add these, I just don't have the devices to test it with (yet)

> - Support for Jailbreaking 64 Bit Devices with SSH Ramdisk iOS 7.0-9.1

Nope, not interested in 64-bit

> - Add iOS 4.3.x iPad 2 Support to g1bertJB

This is planned, maybe if I get a device to test it with, 4.3.x support will eventually be added

Anyway, I'll be closing this issue since it's not really an issue, it's more suitable to be in Discussions
