### ISSUE TITLE
LANGID error when pwning iPhone 5

### ISSUE THREAD

**Issue by fqrums** [LukeZGD/Legacy-iOS-Kit#350]
i get this log
Found:
Traceback (most recent call last):
  File "rmsigchks.py", line 92, in <module>
    main()
  File "rmsigchks.py", line 63, in main
    print "Found:", device.serial_number
  File "/home/koleq/Downloads/iOS-OTA-Downgrader/resources/ipwndfu/usb/core.py", line 830, in serial_number
    self._serial_number = util.get_string(self, self.iSerialNumber)
  File "/home/koleq/Downloads/iOS-OTA-Downgrader/resources/ipwndfu/usb/util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid
when trying to pwn an iphone 5 32gb on xubuntu..
please help

**Comment by LukeZGD** [comment]
checkm8 pwning issues are very common on linux which is why i recommend using a mac or another ios device (https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Pwning-Using-Another-iOS-Device) to use ipwnder.

also make sure that you are using the latest version (v23.11.16). and also, are you sure thats an iphone 5, or is it a 5s since its running rmsigchks (which is only used for a7 devices)

**Comment by fqrums** [comment]
im sure its an iphone 5 cause i actually went into the device and everything, and i dont have access to any macos devices nor can i hackintosh any of my devices, and yes im running latest

**Comment by fqrums** [comment]
installing linux mint to see if something changes ig

**Comment by fqrums** [comment]
pwned just fine, seems like ubuntu just died on me
