### ISSUE TITLE
ERASE IPHONE 64 BIT WITH SSH RAMDISK PART 2 

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#425]
Tried the guide on https://www.reddit.com/r/LegacyJailbreak/wiki/guides/sameioswipe method to erase device using nvram oblit-inprogress=5; exit and reboot device and the device still boots into recovery mode with Legacy iOS Kit, using SSHRD Ramdisk

**Comment by LukeZGD** [comment]
Erase all does not magically fix recovery mode issues,  it could be a different problem not connected. Depending on the situation, your device might be screwed. Since this is out of scope of Legacy iOS Kit, you may want to ask in legacyjailbreak or somewhere else for assistance, especially since I can't help you with this one
