### ISSUE TITLE
Fix Powdersn0w iPad 4 

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#444]

**Comment by LukeZGD** [comment]
See #421. The issue is that I don't really know what's wrong with the current ramdisk, I can't create exploit ramdisks, and there is a much lack of iPad 4 7.0.x that can test this, other than the issue I linked. idk, this is likely to not get fixed, unless someone like m1zole who has done a working 5C 7.0.x ramdisk takes this up to the task
