### ISSUE TITLE
Ubuntu stuffs

### ISSUE THREAD

**Issue by mrgarbagegamer** [LukeZGD/Legacy-iOS-Kit#493]
Upon first configuration, the program tries to install dependencies by adding "universe" to all sources in the source list, but this causes a problem with an Ubuntu LiveCD/persistent profile (it adds it to the cdrom:// source, causing it to always give warnings that universe isn't a component). Can an exception be made in the code to prevent it from adding that to the source? It's not too big of an issue and is easily fixable by editing sources.list to remove the keyword universe from the cdrom source, but it's still an annoyance to have to deal with each time I reset and recreate a liveCD.

**Comment by LukeZGD** [comment]
I use add-apt-repository to add universe to the sources list which is needed, I don't think there is a way to add the cdrom as an exception for it AFAIK

It's not a big issue anyway since it just results in a warning

A workaround is to just use persistent storage or full install to keep changes in the source list
