### ISSUE TITLE
iPod3,1 blob dumping fails

### ISSUE THREAD

**Issue by LeoI07** [LukeZGD/Legacy-iOS-Kit#511]
I'm trying to dump onboard SHSH blobs from an iPod touch (3rd generation) running iPhone OS 3.1.2. Legacy iOS Kit is able to dump blobs for all the firmware files except LLB, and thus it errors out when attempting to convert the raw dump to a .shsh file.

[Terminal output](https://github.com/user-attachments/files/15910148/Terminal.Saved.Output.redacted.txt)
[Raw dump](https://github.com/user-attachments/files/15910187/rawdump_3952344747383-iPod3.1_2024-06-20-0254_.raw.zip)

**Comment by LukeZGD** [comment]
legacy ios kit support onboard blob dump operations for a5 and newer only, it does not work properly on a4 and older (though some a4 devices had success with this)

i have no plans to fix this, especially since there are ways to downgrade these older devices untethered (except for iphone3,2 and touch 4, rip to those)

the only way to dump onboards for these devices currently is to use ifaith (i have seen somewhere on reddit that ifaith 1.0 should work for ios 3.x)
