### ISSUE TITLE
Any plans to add support backing up baseband for ipads?

### ISSUE THREAD

**Issue by platinumstufff** [LukeZGD/Legacy-iOS-Kit#590]
iPad2,2 iOS 5.1.1 never updated. I need to restore it because of jailbreak. And I want my baseband version.

**Comment by LukeZGD** [comment]
It is safe to restore to any version that isn't the latest using Legacy iOS Kit, since your baseband version will be preserved. For more info see the baseband update section here https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Restore-Downgrade

Anyways baseband version does not really matter for A5 and newer devices anyway

**Comment by platinumstufff** [comment]
Oh, I'm blind.
